//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace InterfazSeguridad.wsSeguridad {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsSeguridadSoap", Namespace="http://tempuri.org/")]
    public partial class WsSeguridad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EncriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesencriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback HashingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerLlavesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TarjetasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsSeguridad() {
            this.Url = global::InterfazSeguridad.Properties.Settings.Default.InterfazSeguridad_wsSeguridad_WsSeguridad;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EncriptarCompletedEventHandler EncriptarCompleted;
        
        /// <remarks/>
        public event DesencriptarCompletedEventHandler DesencriptarCompleted;
        
        /// <remarks/>
        public event HashingCompletedEventHandler HashingCompleted;
        
        /// <remarks/>
        public event ObtenerLlavesCompletedEventHandler ObtenerLlavesCompleted;
        
        /// <remarks/>
        public event TarjetasCompletedEventHandler TarjetasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Encriptar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Encriptar(Encriptador encriptador) {
            object[] results = this.Invoke("Encriptar", new object[] {
                        encriptador});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void EncriptarAsync(Encriptador encriptador) {
            this.EncriptarAsync(encriptador, null);
        }
        
        /// <remarks/>
        public void EncriptarAsync(Encriptador encriptador, object userState) {
            if ((this.EncriptarOperationCompleted == null)) {
                this.EncriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncriptarOperationCompleted);
            }
            this.InvokeAsync("Encriptar", new object[] {
                        encriptador}, this.EncriptarOperationCompleted, userState);
        }
        
        private void OnEncriptarOperationCompleted(object arg) {
            if ((this.EncriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncriptarCompleted(this, new EncriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Desencriptar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Desencriptar(Desencriptador desencriptador) {
            object[] results = this.Invoke("Desencriptar", new object[] {
                        desencriptador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesencriptarAsync(Desencriptador desencriptador) {
            this.DesencriptarAsync(desencriptador, null);
        }
        
        /// <remarks/>
        public void DesencriptarAsync(Desencriptador desencriptador, object userState) {
            if ((this.DesencriptarOperationCompleted == null)) {
                this.DesencriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesencriptarOperationCompleted);
            }
            this.InvokeAsync("Desencriptar", new object[] {
                        desencriptador}, this.DesencriptarOperationCompleted, userState);
        }
        
        private void OnDesencriptarOperationCompleted(object arg) {
            if ((this.DesencriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesencriptarCompleted(this, new DesencriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Hashing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Hashing(string CadenaTexto) {
            object[] results = this.Invoke("Hashing", new object[] {
                        CadenaTexto});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void HashingAsync(string CadenaTexto) {
            this.HashingAsync(CadenaTexto, null);
        }
        
        /// <remarks/>
        public void HashingAsync(string CadenaTexto, object userState) {
            if ((this.HashingOperationCompleted == null)) {
                this.HashingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHashingOperationCompleted);
            }
            this.InvokeAsync("Hashing", new object[] {
                        CadenaTexto}, this.HashingOperationCompleted, userState);
        }
        
        private void OnHashingOperationCompleted(object arg) {
            if ((this.HashingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HashingCompleted(this, new HashingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerLlaves", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeneradorLlaves ObtenerLlaves() {
            object[] results = this.Invoke("ObtenerLlaves", new object[0]);
            return ((GeneradorLlaves)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerLlavesAsync() {
            this.ObtenerLlavesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerLlavesAsync(object userState) {
            if ((this.ObtenerLlavesOperationCompleted == null)) {
                this.ObtenerLlavesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerLlavesOperationCompleted);
            }
            this.InvokeAsync("ObtenerLlaves", new object[0], this.ObtenerLlavesOperationCompleted, userState);
        }
        
        private void OnObtenerLlavesOperationCompleted(object arg) {
            if ((this.ObtenerLlavesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerLlavesCompleted(this, new ObtenerLlavesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Tarjetas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Tarjetas(string Tarjeta) {
            object[] results = this.Invoke("Tarjetas", new object[] {
                        Tarjeta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TarjetasAsync(string Tarjeta) {
            this.TarjetasAsync(Tarjeta, null);
        }
        
        /// <remarks/>
        public void TarjetasAsync(string Tarjeta, object userState) {
            if ((this.TarjetasOperationCompleted == null)) {
                this.TarjetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTarjetasOperationCompleted);
            }
            this.InvokeAsync("Tarjetas", new object[] {
                        Tarjeta}, this.TarjetasOperationCompleted, userState);
        }
        
        private void OnTarjetasOperationCompleted(object arg) {
            if ((this.TarjetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TarjetasCompleted(this, new TarjetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Encriptador {
        
        private string plainTextField;
        
        private byte[] keyField;
        
        private byte[] ivField;
        
        /// <remarks/>
        public string PlainText {
            get {
                return this.plainTextField;
            }
            set {
                this.plainTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] IV {
            get {
                return this.ivField;
            }
            set {
                this.ivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneradorLlaves {
        
        private byte[] keyField;
        
        private byte[] ivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Iv {
            get {
                return this.ivField;
            }
            set {
                this.ivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Desencriptador {
        
        private byte[] cipherTextField;
        
        private byte[] keyField;
        
        private byte[] ivField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CipherText {
            get {
                return this.cipherTextField;
            }
            set {
                this.cipherTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] IV {
            get {
                return this.ivField;
            }
            set {
                this.ivField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EncriptarCompletedEventHandler(object sender, EncriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DesencriptarCompletedEventHandler(object sender, DesencriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesencriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesencriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HashingCompletedEventHandler(object sender, HashingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HashingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HashingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ObtenerLlavesCompletedEventHandler(object sender, ObtenerLlavesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerLlavesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerLlavesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneradorLlaves Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneradorLlaves)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TarjetasCompletedEventHandler(object sender, TarjetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TarjetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TarjetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591